### ISSUE TITLE
Renaming suggestion

### ISSUE THREAD

**Issue by brandmaier** [Lifebrain/metagam#1]
Rename the column containing point estimates in `prediction`-tibble in return object of metagam. It's currently called "fit" (one may confuse this with model git). Rather call it `est` for estimate or simply `y`.

**Comment by osorensen** [comment]
Thanks, very good point! I will update it. 

Also, I am not entirely happy with the function name `prepare_meta`, used to remove individual participant data from the `gam` object. If you have any suggestions for a better name, I am very happy.

**Comment by brandmaier** [comment]
what about `strip_rawdata` - or is there any extra functionality?

**Comment by drmowinckels** [comment]
or `anonymize_rawdata`

**Comment by osorensen** [comment]
I like `strip_rawdata`, since this is what we remove. When looking into the `gam` objects I have seen that there are also many objects that can reveal the raw data, for example evaluation of the splines at each individual data point, or the residual at each point (which I guess would reveal the raw response in an intercept-only model). So perhaps `strip_ipd`, where "IPD" stands for Individual Participant Data could be an option too.
